# KFold Cross Validation Python Tutorial

This is a self-exercise notebook that was created while following along in the following YouTube video by codebasics:

Machine Learning Tutorial Python 12 - K Fold Cross Validation 
  + https://www.youtube.com/watch?v=gJo0uNL-5Qw


In [133]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt


import warnings
warnings.filterwarnings("ignore")

digits = load_digits()

In [134]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

__Logistic Regression__

In [135]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.95

__SVM__

In [136]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.3055555555555556

__Random Forst__

In [137]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9777777777777777

---
---
---
### Now, lets implement K Fold

In [138]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [139]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [140]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [141]:
#get_score(SVC(), X_train, X_test, y_train, y_test)

In [142]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [143]:
X_train.shape

(1257, 64)

In [144]:
y_train.shape


(1257,)

In [145]:
scores_logistic = []
scores_svm = []
scores_rf = []



for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [146]:
scores_logistic

[0.8953488372093024, 0.9499165275459098, 0.9093959731543624]

In [147]:
scores_svm

[0.39368770764119604, 0.41068447412353926, 0.4597315436241611]

In [148]:
scores_rf

[0.920265780730897, 0.9582637729549248, 0.9295302013422819]

## cross_val_score function

cross_val_score is the short hand notation for the same code we just wrote above. 

__Note:__ cross_val_score uses stratified kfold by default.

In [149]:
from sklearn.model_selection import cross_val_score

__Logistic regression model performance using cross_val_score__

In [150]:
cross_val_score(LogisticRegression(solver='liblinear', multi_class='ovr'), digits.data, digits.target, cv=3)

array([0.89534884, 0.94991653, 0.90939597])

__svm model performance using cross_val_score__

In [151]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target, cv=3)

array([0.39368771, 0.41068447, 0.45973154])

__random forest performance using cross_val_score__

In [152]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

array([0.91694352, 0.96160267, 0.93624161])

## Parameter tuning using k fold cross validation (cross_val_score)

In [153]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8715044696282052

In [154]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9387963285412088

In [155]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.9460413507853781

In [156]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=50),digits.data, digits.target, cv=10)
np.average(scores4)

0.9527550429805622

---
---
---
We see from our parameter tuning that 50 trees in the random forest gives the best results.